fusion_estimator:
  Initial_State_X:  0.0
  Initial_State_Y:  0.0
  Initial_State_Z:  0.1
  Initial_State_Roll:  0
  Initial_State_Pitch: 0
  Initial_State_Yaw:   -0.13
  urdf_file_name: "FusionEstimator/cfg/go2_description.urdf"
  urdf_file_package: "ocs2_robotic_assets"
  urdf_BaseName: "base"
  urdf_HipJointName: "FL_hip_joint"
  urdf_HipLengthName: "FL_thigh_joint"
  urdf_ThighLengthName: "FL_calf_joint"
  urdf_CalfLengthName: "FL_calflower_joint"
  urdf_FootLengthName: "FL_foot"
  FootForce_Threshold: 1
  Sensor_Signal_Source_1: "/low_state"
  Sensor_Signal_Source_2: "/odom"
  frequency: 400